"""empty message

Revision ID: 55fc14265d74
Revises: c03f197c2c9a
Create Date: 2022-11-24 16:08:27.132516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fc14265d74'
down_revision = 'c03f197c2c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_looking_for_venues')

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('genres')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
