"""empty message

Revision ID: 82512e323385
Revises: 6162c169102e
Create Date: 2022-11-25 12:02:27.911958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82512e323385'
down_revision = '6162c169102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
