"""empty message

Revision ID: 8be54c2a4d23
Revises: 1178d6c9b5f2
Create Date: 2022-11-25 23:50:31.659343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8be54c2a4d23'
down_revision = '1178d6c9b5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_artist_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shows_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.create_foreign_key('shows_venue_id_fkey', 'venues', ['venue_id'], ['id'])
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('start_time')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
